### ISSUE TITLE
react 19

### ISSUE THREAD

**Issue by bardak-dev** [betula/use-between#47]
привет! клёвая либа но что мы будем с ней делать на 19 версии ректа?)

**Comment by betula** [comment]
Hello,
Can you explain more about your problem with React 19?

**Comment by bardak-dev** [comment]
https://react.dev/blog/2024/04/25/react-19-upgrade-guide#libraries-depending-on-react-internals-may-block-upgrades

**Comment by designbyadrian** [comment]
After upgrading to React 19, I'm presented with this error:

```
TypeError: Cannot read properties of undefined (reading 'ReactCurrentDispatcher')
    at Object.<anonymous> (/Users/attila/Repositories/@london-dynamics/cms/node_modules/use-between/release/index.js:28:53)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at cjsLoader (node:internal/modules/esm/translators:366:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:315:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async nodeImport (file:///Users/attila/Repositories/@london-dynamics/cms/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:52999:15)
```

**Comment by betula** [comment]
If you've done something, but it's not yet working, feel free to submit a PR and we'll review it together. Each of your contributions gives me a boost of strength and motivation!🤗🍀🚀

**Comment by bardak-dev** [comment]
@betula take a look at https://www.npmjs.com/package/use-mono-hook
the is no docs yet but it has support all react hooks, context, etc
basic usage is
```ts
import { MonoHooksStore } from 'use-mono-hook'
createRoot(document.getElementById('root')).render(
  <>
    <App />
    <MonoHooksStore />
  </>
)
```

```ts
import {createMonoHook,} from 'use-mono-hook';
import { useState} from 'react';

const _useProfile = () => {
  const [profile, setProfile] = useState();
  return {
    profile,
    setProfile,
  };
};

export const useProfile = createMonoHook<typeof _useProfile>(_useProfile, {
  defaults: {
    profile: undefined,
  }
}).useHook; // also has useHookWithArguments to use hook with params

```
under the hood there is react context and syncExternalStore no additional "rewrite everything" logic
also works in react native with HMR (there is a hitch to track changes inside functions because of HermesJS engine)
only 1 limitation is persist that and cannot be resolve I think, because execute function after useEffect no data on initial render, I tried bypass this by react-suspend but no luck because react render rules (it works but errors in console can be omited so no implementation of instant data on initial render is possible)

**Comment by betula** [comment]
Hi @bardak-dev ,

Welcome to the team of state management enthusiasts 😊

The `use-mono-hook` looks very nice, but it doesn't follow the paradigm of minimal syntax. At the start, it's necessary to connect the `MonoHooksStore` and also wrap every hook used in `createMonoHook` beforehand, alongside the hook's function. This makes it a bit more complex rather than very simple. In this regard, I prefer `use-between` more. 😉

I really liked another piece of your code from your GitHub; you've already written half of what is crucial now for `use-between`. 🤗

I'm talking about:
[https://github.com/stigma-io/use-mono](https://github.com/stigma-io/use-mono)

You've already done part of the work necessary to support React 19; you renamed the key through which the `ReactSharedInternal` object of React is exported. You only need to do a second renaming:

[https://github.com/stigma-io/use-mono/commit/b742b5d98c9604926e63f712f7630e8cf9b7d70a#diff-42ec483a33163db3a8dff6c478b01ce94e57e1f9299714aa42cda6963442b7d3R13](https://github.com/stigma-io/use-mono/commit/b742b5d98c9604926e63f712f7630e8cf9b7d70a#diff-42ec483a33163db3a8dff6c478b01ce94e57e1f9299714aa42cda6963442b7d3R13)

The signature of the type `ReactSharedInternalTypes` has changed. You can see the new one on GitHub React here:

[https://github.com/facebook/react/blob/main/packages/react/src/ReactSharedInternalsClient.js#L25](https://github.com/facebook/react/blob/main/packages/react/src/ReactSharedInternalsClient.js#L25)

If you look closely, the field that was previously called `ReactCurrentDispatcher` inside this "secret" object is now renamed to `H`, probably to confuse its users. The `ReactCurrentDispatcher` property is now simply called `H`. This is essentially enough for `use-between` to start supporting React 19 in its previous form.

You'll just need to make sure both the old and new properties work, and everything will be complete and functional for React 19.

**Comment by betula** [comment]
Awesome!
Thanks a lot!
I'll merge it on the weekend!

**Comment by betula** [comment]
I've fixed the tests and worked quite a bit on moving away from the outdated Enzyme, but now everything is fine.  
The tests are passing, everything is green! 👍

I'll be building the version soon 🍀

Thanks to everyone who pushed this topic, React 19 support in `use-between` is coming soon. 🎉

Enjoy and Happy Coding 😇🍀

**Comment by betula** [comment]
# Wonderful News

I have released version `1.4.0` for `use-between`.

Now React 19 is also supported! Hooray 🎉

Special thanks to @shsr04

[react 17 supported](https://codesandbox.io/p/sandbox/test-use-between-1-4-0-17-3hd3hq)
[react 18 supported](https://codesandbox.io/p/sandbox/test-use-between-1-4-0-18-rcydzs)
[react 19 supported](https://codesandbox.io/p/sandbox/relaxed-marco-tk3jsm)

You can keep improving your projects and keep up with the times.

Enjoy your code!
